version: 0.2

run-as: root

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - echo Login to Amazon ECR Successful!
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t linux_tweet_app:latest .
      - docker tag linux_tweet_app:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/linux_tweet_app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/linux_tweet_app:latest
      - echo Push Successful!

artifacts:
  files:
    - "**/*"
